'use strict'

exports.SET_GROUP = '/setgroup'
exports.CREATE_TRAINING = '/createtraining'
exports.HELP = '/help'
exports.START = '/start'
exports.CREATE_GROUP = '/creategroup'
exports.CHANGE_GROUP_TIME = '/changegrooptime'
exports.INFO = '/info'
exports.FORCE = '/force'